### ISSUE TITLE
Do not try to package containeRit itself

### ISSUE THREAD

**Issue by nuest** [o2r-project/containerit#49]
It is completely correct that right now there is an error message when a session is packaged, because containeRit itself is not published online: "Failed to identify source for package containeRit. Therefore the package cannot be installed in the docker image."

However, it should _not_ be common to "package the packaging lib", so we should add an option `add_self = false` to the `dockerfile(..)` function that does by default not try to add the containeRit package itself to the image.

**Comment by MatthiasHinz** [comment]
Alright.

Note that we still cannot avoid packaging those package that depend on the packaging lib once they are loaded or attached to the session because we cannot rule out whether the user might require one of them as well.

However, we _already can_ rule out unnecessary dependencies when packaging R scripts, containeRit runs these script in a separate local R session from which the session information is then obtained.
