### ISSUE TITLE
Package any RMarkdown file

### ISSUE THREAD

**Issue by nuest** [o2r-project/containerit#9]
~~- [ ] https://github.com/o2r-project/o2r-muncher/tree/master/test/bagtainers/markdowntainer-sfr/data~~
- [x] https://github.com/o2r-project/o2r-muncher/tree/master/test/bagtainers/markdowntainer-units/data
- [x] test for vignette sf3 from sf-package (available by `system.file("doc/sf3.Rmd",package = "sf")`) 
- [x] test for `system.file("examples", "knitr-minimal.Rnw", package = "knitr")`

**Comment by MatthiasHinz** [comment]
There are multiple issues with the markdown file in `markdowntainer-sfr`:

- I am not able to install the latest 'rgdal2' from gitbub (i.e. via `devtools::install_github("thk686/rgdal2")` or `devtools::install_github("thk686/rgdal2"`)), even when going back to previous commits. Perhaps it's a problem roxygen2. Therfore, I am not able to render the markdown even locally
--> Issue: https://github.com/thk686/rgdal2/issues/9

- The sf-library requires up-to-date versions of proj4 and gdal, therefore the installation via apt-get is not sufficient. Neither does the sysreqs-package supply such information, so the packaging would fail at the moment. There are two workarounds:
  1) Use the `rocker/geospatial `image where these system-dependencies are pre-installed
  2) When 'sf' is required, install proj4 and gdal from source if not pre-installed.

- Currently, we may have concurrent versions of proj4 and gdal, because apt-get will install the packages even if newer versions of them were installed from source. However, from my testing, always the latest versions of gdal/proj are detected, so that the configuration will still work like this and the problem can be treated as a minor issue.

**Comment by edzer** [comment]
@MatthiasHinz I don't think you'll need `rgdal2`, it is not being used in real life projects. 

For `sf`, a third alternative (assuming you use ubuntu) is to use ubuntugis; see sfr's [travis file](https://github.com/edzer/sfr/blob/master/.travis.yml). 

Installing stuff from source by default puts it in `/usr/local/`, where apt-get puts it in `/usr/`; normally `/usr/local/` is searched first for including, linking or running. 

I think it is considered good scientific practice to use R packages from CRAN, rather than from github, since you can't mess with its archive.

**Comment by MatthiasHinz** [comment]
@edzer Thank you for the hints! I did not know about the installation behavior, especially. It's clear that CRAN is the preferred repository to use, but still, we also want to support GitHub installations.

The point is that we planned to use the markdown document above for our test-cases. But now I realize that it's not a good example. We require any code that we containerize to run at least on our local system so that we can detect the dependencies for the Dockerfile, and this is not given. Also, the test-markdown relies on an outdated version of 'sf' and we couldn't handle this as a dependency for an integrated package test. So, maybe I should leave it and use something else for testing.
